"""Design data dictionary and deterministic MySQL DDL; not a deployed migration."""
T={}
def c(typ, nullable=False, default=None, description='', generated=None):
    return dict(type=typ,nullable=nullable,default_sql=default,description=description,generated_sql=generated)
def uid(nullable=False):return c('CHAR(36)',nullable)
def dt(nullable=False):return c('DATETIME(3)',nullable)
def s(n=200,nullable=False):return c('VARCHAR('+str(n)+')',nullable)
def num(default='0'):return c('INT UNSIGNED',False,default)
def state(*v):return c('ENUM('+','.join("'"+x+"'" for x in v)+')',False,"'"+v[0]+"'")
def j():return c('JSON')
def table(name,fields,unique=(),indexes=(),checks=(),tenant=True,immutable=False):
    cols={'id':uid(),'created_at':c('DATETIME(3)',False,'CURRENT_TIMESTAMP(3)'),
          'updated_at':c('DATETIME(3)',False,'CURRENT_TIMESTAMP(3)'), 'version':num('1')}
    if tenant:cols['tenant_id']=uid()
    cols.update(fields)
    T[name]=dict(columns=cols,primary_key=['id'],unique=([['tenant_id','id']] if tenant else [])+[list(x) for x in unique],indexes=[list(x) for x in indexes],foreign_keys=[],checks=list(checks),append_only=immutable)
    if tenant:fk(name,['tenant_id'],'tenants',['id'])
def fk(src,cols,dst,refs):T[src]['foreign_keys'].append(dict(columns=cols,target=dst,references=refs,on_delete='RESTRICT',on_update='RESTRICT'))
def link(src,col,dst,scope=()):fk(src,['tenant_id',*scope,col],dst,['tenant_id',*scope,'id'])
def build_database():
    T.clear()
    table('tenants',{'code':s(64),'name':s(),'timezone':s(64),'status':state('active','suspended')},unique=[['code']],tenant=False)
    table('roles',{'code':s(40),'name':s(100)},unique=[['code']],tenant=False)
    table('colleges',{'code':s(64),'name':s(),'status':state('active','archived')},unique=[['tenant_id','code']])
    table('laboratories',{'college_id':uid(),'code':s(64),'name':s(),'status':state('active','archived')},unique=[['tenant_id','code']]);link('laboratories','college_id','colleges')
    table('users',{'username':s(128),'display_name':s(100),'password_hash':s(255),'status':state('active','disabled'),'session_epoch':num()},unique=[['tenant_id','username']])
    table('user_roles',{'user_id':uid(),'role_id':uid(),'laboratory_id':uid(True),'scope_kind':state('tenant','laboratory'),'scope_key':c('CHAR(36)',generated="COALESCE(laboratory_id,'00000000-0000-0000-0000-000000000000')")},unique=[['tenant_id','user_id','role_id','scope_key']],checks=["(scope_kind='tenant' AND laboratory_id IS NULL) OR (scope_kind='laboratory' AND laboratory_id IS NOT NULL)"])
    link('user_roles','user_id','users');link('user_roles','laboratory_id','laboratories');fk('user_roles',['role_id'],'roles',['id'])
    table('sessions',{'user_id':uid(),'token_hash':c('CHAR(64)'),'csrf_hash':c('CHAR(64)'),'session_epoch':num(),'expires_at':dt(),'idle_expires_at':dt(),'revoked_at':dt(True)},unique=[['token_hash']],indexes=[['expires_at']]);link('sessions','user_id','users')
    table('locations',{'laboratory_id':uid(),'parent_id':uid(True),'type':state('room','area','shelf','cabinet'),'label':s(),'status':state('active','archived')},unique=[['tenant_id','laboratory_id','id']]);link('locations','laboratory_id','laboratories');link('locations','parent_id','locations',['laboratory_id'])
    table('inspection_templates',{'family_id':uid(),'revision':num('1'),'name':s(),'status':state('draft','published','retired')},unique=[['tenant_id','family_id','revision']])
    table('template_items',{'template_id':uid(),'code':s(64),'title':s(),'capture_hint':s(1000),'sort_order':num(),'required':c('BOOLEAN',False,'TRUE')},unique=[['tenant_id','template_id','code'],['tenant_id','template_id','id']]);link('template_items','template_id','inspection_templates')
    table('inspections',{'laboratory_id':uid(),'template_id':uid(),'inspector_id':uid(),'status':state('draft','in_progress','completed','cancelled'),'completed_at':dt(True)},unique=[['tenant_id','laboratory_id','id']]);link('inspections','laboratory_id','laboratories');link('inspections','template_id','inspection_templates');link('inspections','inspector_id','users')
    table('inspection_items',{'inspection_id':uid(),'laboratory_id':uid(),'template_item_id':uid(),'location_id':uid(),'status':state('draft','uploaded','queued','quality_checking','needs_retake','processing','needs_review','completed','failed'),'submission_revision':num(),'current_run_id':uid(True),'current_fact_revision_id':uid(True),'current_evaluation_id':uid(True),'review_outcome':c("ENUM('no_issue','issues_confirmed','cannot_determine')",True),'reviewed_by':uid(True),'reviewed_at':dt(True)},unique=[['tenant_id','laboratory_id','id'],['tenant_id','inspection_id','template_item_id','location_id']])
    link('inspection_items','inspection_id','inspections',['laboratory_id']);link('inspection_items','template_item_id','template_items');link('inspection_items','location_id','locations',['laboratory_id']);link('inspection_items','reviewed_by','users')
    table('dictionary_versions',{'version_label':s(64),'checksum':c('CHAR(64)'),'object_key':s(1024),'source':s(2000),'status':state('draft','published','retired')},unique=[['tenant_id','version_label']])
    table('chemical_entities',{'dictionary_version_id':uid(),'canonical_name':s(),'cas_number':s(32,True),'hazard_class':s(80),'storage_class':s(80)},unique=[['tenant_id','dictionary_version_id','id']],immutable=True);link('chemical_entities','dictionary_version_id','dictionary_versions')
    table('chemical_aliases',{'dictionary_version_id':uid(),'entity_id':uid(),'normalized_alias':s()},unique=[['tenant_id','dictionary_version_id','entity_id','normalized_alias']],immutable=True);link('chemical_aliases','entity_id','chemical_entities',['dictionary_version_id'])
    table('model_versions',{'name':s(100),'bundle_version':s(64),'dictionary_version_id':uid(),'checksum':c('CHAR(64)'),'manifest':j(),'status':state('registered','validated','published','retired'),'evaluation_report_key':s(1024,True)},unique=[['tenant_id','bundle_version']]);link('model_versions','dictionary_version_id','dictionary_versions')
    table('rule_sets',{'name':s(),'description':s(2000)},unique=[['tenant_id','name']])
    table('rule_versions',{'rule_set_id':uid(),'revision':num('1'),'checksum':c('CHAR(64)'),'definition':j(),'status':state('draft','submitted','approved','published','retired'),'submitted_by':uid(True),'approved_by':uid(True),'approved_at':dt(True)},unique=[['tenant_id','rule_set_id','revision']]);link('rule_versions','rule_set_id','rule_sets');link('rule_versions','submitted_by','users');link('rule_versions','approved_by','users')
    table('rule_bundles',{'checksum':c('CHAR(64)'),'evaluator_version':s(64)},unique=[['tenant_id','checksum']],immutable=True)
    table('rule_bundle_members',{'bundle_id':uid(),'rule_version_id':uid()},unique=[['tenant_id','bundle_id','rule_version_id']],immutable=True);link('rule_bundle_members','bundle_id','rule_bundles');link('rule_bundle_members','rule_version_id','rule_versions')
    table('activations',{'laboratory_id':uid(),'model_bundle_id':uid(),'dictionary_version_id':uid(),'rule_bundle_id':uid(),'pipeline_version':s(64),'device_profile':state('cpu','cuda')},unique=[['tenant_id','laboratory_id']]);link('activations','laboratory_id','laboratories');link('activations','model_bundle_id','model_versions');link('activations','dictionary_version_id','dictionary_versions');link('activations','rule_bundle_id','rule_bundles')
    table('inference_runs',{'item_id':uid(),'laboratory_id':uid(),'submission_revision':num('1'),'replay_of':uid(True),'input_hash':c('CHAR(64)'),'model_bundle_id':uid(),'dictionary_version_id':uid(),'rule_bundle_id':uid(),'pipeline_version':s(64),'device_profile':state('cpu','cuda'),'reference_date':c('DATE'),'status':state('queued','processing','retrying','completed','needs_retake','needs_review','failed','superseded'),'stage':state('queued','quality','facts','rules','done'),'result':c('JSON',True),'result_hash':c('CHAR(64)',True),'error_code':s(80,True),'started_at':dt(True),'finished_at':dt(True)},unique=[['tenant_id','item_id','id'],['tenant_id','item_id','submission_revision']]);link('inference_runs','item_id','inspection_items',['laboratory_id']);link('inference_runs','replay_of','inference_runs');link('inference_runs','model_bundle_id','model_versions');link('inference_runs','dictionary_version_id','dictionary_versions');link('inference_runs','rule_bundle_id','rule_bundles')
    table('fact_revisions',{'item_id':uid(),'run_id':uid(),'revision':num('1'),'entities':j(),'relations':j(),'dates':j(),'reason':s(2000),'created_by':uid(True)},unique=[['tenant_id','item_id','id'],['tenant_id','run_id','revision']],immutable=True);link('fact_revisions','run_id','inference_runs',['item_id']);link('fact_revisions','created_by','users')
    table('rule_evaluations',{'item_id':uid(),'run_id':uid(),'fact_revision_id':uid(),'rule_bundle_id':uid(),'reference_date':c('DATE'),'status':state('queued','running','completed','failed','superseded'),'result':c('JSON',True),'result_hash':c('CHAR(64)',True),'finished_at':dt(True)},unique=[['tenant_id','item_id','id'],['tenant_id','fact_revision_id','rule_bundle_id']]);link('rule_evaluations','run_id','inference_runs',['item_id']);link('rule_evaluations','fact_revision_id','fact_revisions',['item_id']);link('rule_evaluations','rule_bundle_id','rule_bundles')
    for col,dst in [('current_run_id','inference_runs'),('current_fact_revision_id','fact_revisions'),('current_evaluation_id','rule_evaluations')]:fk('inspection_items',['tenant_id','id',col],dst,['tenant_id','item_id','id'])
    table('findings',{'item_id':uid(),'run_id':uid(),'fact_revision_id':uid(),'rule_evaluation_id':uid(),'rule_id':s(80),'fingerprint':c('CHAR(64)'),'type':s(80),'severity':state('low','medium','high','critical'),'status':state('needs_review','confirmed','rejected','cannot_determine','dispatched','closed'),'explanation':s(4000),'evidence':j(),'superseded_at':dt(True),'confirmed_by':uid(True)},unique=[['tenant_id','rule_evaluation_id','fingerprint']]);link('findings','run_id','inference_runs',['item_id']);link('findings','fact_revision_id','fact_revisions',['item_id']);link('findings','rule_evaluation_id','rule_evaluations',['item_id']);link('findings','confirmed_by','users')
    table('review_actions',{'actor_id':uid(),'resource_type':s(80),'resource_id':uid(),'action':s(80),'reason':s(2000),'before_version':num('1'),'after_version':num('1')},immutable=True);link('review_actions','actor_id','users')
    table('remediation_tasks',{'finding_id':uid(),'laboratory_id':uid(),'assignee_id':uid(),'status':state('pending_dispatch','in_progress','pending_recheck','rejected','cannot_remediate','closed'),'priority':state('low','medium','high','critical'),'due_at':dt(),'description':s(4000),'latest_evidence_id':uid(True),'closed_at':dt(True)},unique=[['tenant_id','finding_id'],['tenant_id','laboratory_id','id']]);link('remediation_tasks','finding_id','findings');link('remediation_tasks','laboratory_id','laboratories');link('remediation_tasks','assignee_id','users')
    table('remediation_evidence',{'task_id':uid(),'description':s(4000),'submitted_by':uid()},unique=[['tenant_id','task_id','id']],immutable=True);link('remediation_evidence','task_id','remediation_tasks');link('remediation_evidence','submitted_by','users');fk('remediation_tasks',['tenant_id','id','latest_evidence_id'],'remediation_evidence',['tenant_id','task_id','id'])
    owner={'laboratory_id':uid(),'inspection_item_id':uid(True),'remediation_task_id':uid(True)}
    table('uploads',{**owner,'requested_by':uid(),'object_key':s(1024),'expected_sha256':c('CHAR(64)'),'mime_type':s(40),'size_bytes':c('BIGINT UNSIGNED'),'captured_at':dt(),'expires_at':dt(),'status':state('granted','validating','ready','rejected','expired')},checks=['(inspection_item_id IS NULL) <> (remediation_task_id IS NULL)']);link('uploads','requested_by','users')
    table('asset_images',{**owner,'upload_id':uid(),'status':state('validating','ready','rejected','deleted'),'original_key':s(1024),'original_object_version':s(200),'original_sha256':c('CHAR(64)'),'analysis_key':s(1024,True),'analysis_object_version':s(200,True),'analysis_sha256':c('CHAR(64)',True),'width':c('INT UNSIGNED',True),'height':c('INT UNSIGNED',True),'mime_type':s(40),'captured_at':dt(),'legal_hold':c('BOOLEAN',False,'FALSE'),'deleted_at':dt(True)},unique=[['tenant_id','upload_id'],['tenant_id','inspection_item_id','id'],['tenant_id','remediation_task_id','id']],checks=['(inspection_item_id IS NULL) <> (remediation_task_id IS NULL)']);link('asset_images','upload_id','uploads')
    for tab in ['uploads','asset_images']:
        link(tab,'laboratory_id','laboratories');link(tab,'inspection_item_id','inspection_items',['laboratory_id']);link(tab,'remediation_task_id','remediation_tasks',['laboratory_id'])
    table('evidence_images',{'task_id':uid(),'evidence_id':uid(),'image_id':uid(),'ordinal':num()},unique=[['tenant_id','evidence_id','image_id'],['tenant_id','evidence_id','ordinal']],immutable=True);link('evidence_images','evidence_id','remediation_evidence',['task_id']);fk('evidence_images',['tenant_id','task_id','image_id'],'asset_images',['tenant_id','remediation_task_id','id'])
    table('run_images',{'item_id':uid(),'run_id':uid(),'image_id':uid(),'ordinal':num(),'role':state('overview','detail'),'parent_image_id':uid(True),'analysis_sha256':c('CHAR(64)')},unique=[['tenant_id','run_id','image_id'],['tenant_id','run_id','ordinal']],immutable=True);link('run_images','run_id','inference_runs',['item_id']);fk('run_images',['tenant_id','item_id','image_id'],'asset_images',['tenant_id','inspection_item_id','id']);fk('run_images',['tenant_id','run_id','parent_image_id'],'run_images',['tenant_id','run_id','image_id'])
    table('image_derivatives',{'run_id':uid(),'image_id':uid(),'crop_id':uid(),'detection_id':uid(),'kind':state('crop'),'recipe':j(),'object_key':s(1024),'object_version':s(200),'sha256':c('CHAR(64)')},unique=[['tenant_id','run_id','crop_id']],immutable=True);fk('image_derivatives',['tenant_id','run_id','image_id'],'run_images',['tenant_id','run_id','image_id'])
    table('api_idempotency',{'actor_id':uid(),'method':s(10),'path_hash':c('CHAR(64)'),'key_hash':c('CHAR(64)'),'request_hash':c('CHAR(64)'),'state':state('pending','completed'),'response_status':c('SMALLINT UNSIGNED',True),'response':c('JSON',True),'lease_owner':uid(True),'lease_until':dt(True),'expires_at':dt()},unique=[['tenant_id','actor_id','method','path_hash','key_hash']],indexes=[['expires_at']]);link('api_idempotency','actor_id','users')
    table('outbox_events',{'event_type':s(80),'aggregate_type':s(80),'aggregate_id':uid(),'aggregate_version':num('1'),'payload':j(),'state':state('pending','leased','published'),'lease_owner':uid(True),'lease_until':dt(True),'attempts':num(),'available_at':dt(),'published_at':dt(True)},indexes=[['state','available_at','id'],['state','lease_until']])
    table('event_inbox',{'event_id':uid(),'consumer':s(80),'processed_at':dt()},unique=[['tenant_id','event_id','consumer']]);link('event_inbox','event_id','outbox_events')
    table('task_runs',{'task_type':s(80),'resource_id':uid(),'logical_key':s(200),'payload':j(),'state':state('ready','leased','retry_wait','succeeded','failed','dead_letter'),'attempt':num(),'replay_generation':num(),'dispatch_sequence':num('1'),'lease_owner':uid(True),'lease_until':dt(True),'fencing_token':c('BIGINT UNSIGNED',False,'0'),'heartbeat_at':dt(True),'available_at':dt(),'last_dispatched_at':dt(True),'last_error_code':s(80,True),'started_at':dt(True),'finished_at':dt(True)},unique=[['tenant_id','logical_key']],indexes=[['state','available_at','id'],['state','lease_until']],checks=['attempt <= 4'])
    table('task_attempts',{'task_id':uid(),'replay_generation':num(),'attempt':num('1'),'fencing_token':c('BIGINT UNSIGNED'),'lease_owner':uid(),'started_at':dt(),'finished_at':dt(True),'status':state('running','succeeded','failed','abandoned'),'error_code':s(80,True)},unique=[['tenant_id','task_id','replay_generation','attempt']]);link('task_attempts','task_id','task_runs')
    table('notifications',{'event_id':uid(),'recipient_id':uid(),'type':s(80),'resource_type':s(80),'resource_id':uid(),'read_at':dt(True)},unique=[['tenant_id','event_id','recipient_id']]);link('notifications','event_id','outbox_events');link('notifications','recipient_id','users')
    table('audit_events',{'actor_id':uid(True),'action':s(100),'resource_type':s(80),'resource_id':uid(),'changes':j(),'reason':s(2000),'request_id':uid()},indexes=[['tenant_id','resource_type','resource_id','created_at']],immutable=True);link('audit_events','actor_id','users')
    table('report_exports',{'requested_by':uid(),'format':state('csv','pdf'),'filters':j(),'snapshot_at':dt(),'snapshot':j(),'status':state('queued','running','ready','failed','expired'),'object_key':s(1024,True),'checksum':c('CHAR(64)',True),'expires_at':dt(True),'last_error_code':s(80,True)});link('report_exports','requested_by','users')
    table('dataset_versions',{'name':s(100),'checksum':c('CHAR(64)'),'manifest_key':s(1024),'authorization_ref':s(1000),'status':state('draft','frozen','retired')},unique=[['tenant_id','name']],immutable=True)
    table('dataset_images',{'dataset_id':uid(),'image_id':uid(),'scene_id':s(100),'split':state('train','validation','test'),'annotation_key':s(1024),'provenance':s(2000)},unique=[['tenant_id','dataset_id','image_id']],immutable=True);link('dataset_images','dataset_id','dataset_versions');link('dataset_images','image_id','asset_images')
    q=lambda x:chr(96)+x+chr(96)
    identifiers=lambda names:', '.join(q(x) for x in names)
    ddl=['-- Design-only MySQL 8.0.16+ / InnoDB DDL. Run in a new empty schema.','-- Application transactions enforce documented cross-resource and JSON invariants.','SET time_zone = \'+00:00\';']
    for name,t in T.items():
        lines=[]
        for col,v in t['columns'].items():
            z=q(col)+' '+v['type']
            if v['generated_sql']:
                z+=' GENERATED ALWAYS AS ('+v['generated_sql']+') STORED'
                z+=' NULL' if v['nullable'] else ' NOT NULL'
            else:
                z+=' NULL' if v['nullable'] else ' NOT NULL'
                if v['default_sql'] is not None:z+=' DEFAULT '+v['default_sql']
            lines.append(z)
        lines.append('PRIMARY KEY ('+identifiers(t['primary_key'])+')')
        for i,u in enumerate(t['unique']):lines.append('UNIQUE KEY '+q('uq_'+name+'_'+str(i))+' ('+identifiers(u)+')')
        for i,u in enumerate(t['indexes']):lines.append('KEY '+q('ix_'+name+'_'+str(i))+' ('+identifiers(u)+')')
        for i,v in enumerate(t['checks']):lines.append('CONSTRAINT '+q('ck_'+name+'_'+str(i))+' CHECK ('+v+')')
        ddl.append('CREATE TABLE '+q(name)+' (\n  '+',\n  '.join(lines)+'\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;')
    for name,t in T.items():
        for i,f in enumerate(t['foreign_keys']):
            ddl.append('ALTER TABLE '+q(name)+' ADD CONSTRAINT '+q('fk_'+name+'_'+str(i))+' FOREIGN KEY ('+identifiers(f['columns'])+') REFERENCES '+q(f['target'])+' ('+identifiers(f['references'])+') ON DELETE RESTRICT ON UPDATE RESTRICT;')
    return dict(version='1.1.0',engine='MySQL 8.0.16+ / InnoDB',timezone='UTC',tables=T),'\n\n'.join(ddl)+'\n'
